# Generated by Django 2.0 on 2017-12-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20171227_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passworld',
            new_name='password',
        ),
    ]
